-- 表/列中文备注（与 schema.prisma /// 注释同步）

ALTER TABLE `users` COMMENT = 'C 端用户表';
ALTER TABLE `users`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '用户主键 ID',
  MODIFY COLUMN `phone` VARCHAR(20) NOT NULL COMMENT '手机号（登录账号）',
  MODIFY COLUMN `password` VARCHAR(255) NOT NULL COMMENT '密码 bcrypt 哈希',
  MODIFY COLUMN `nickname` VARCHAR(64) NULL COMMENT '昵称',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间';

ALTER TABLE `admins` COMMENT = '管理后台管理员';
ALTER TABLE `admins`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '管理员主键 ID',
  MODIFY COLUMN `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  MODIFY COLUMN `password` VARCHAR(255) NOT NULL COMMENT '密码 bcrypt 哈希',
  MODIFY COLUMN `role` VARCHAR(32) NOT NULL COMMENT '角色 SUPER / OPERATOR',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE `brands` COMMENT = '商品品牌';
ALTER TABLE `brands`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '品牌主键 ID',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '品牌名称',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE `categories` COMMENT = '商品类目（树形）';
ALTER TABLE `categories`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '类目主键 ID',
  MODIFY COLUMN `parent_id` INTEGER NULL COMMENT '父类目 ID，一级类目为空',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '类目名称',
  MODIFY COLUMN `level` INTEGER NOT NULL DEFAULT 1 COMMENT '层级 1=一级 2=二级 …',
  MODIFY COLUMN `sort` INTEGER NOT NULL DEFAULT 0 COMMENT '排序权重，越大越靠前',
  MODIFY COLUMN `path` VARCHAR(255) NOT NULL COMMENT '祖先路径，如 /1/2/',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE `spus` COMMENT = '商品 SPU 主表（对齐 goods 主表字段）';
ALTER TABLE `spus`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '商品主键 ID',
  MODIFY COLUMN `goods_sn` VARCHAR(64) NULL COMMENT '商品货号，唯一',
  MODIFY COLUMN `category_id` INTEGER NOT NULL COMMENT '叶子类目 ID（关联 categories）',
  MODIFY COLUMN `title` VARCHAR(255) NOT NULL COMMENT '商品名称 goods_name',
  MODIFY COLUMN `short_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '短标题',
  MODIFY COLUMN `subtitle` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '副标题/卖点',
  MODIFY COLUMN `description` TEXT NULL COMMENT '详情描述',
  MODIFY COLUMN `brand_id` INTEGER NULL COMMENT '品牌 ID',
  MODIFY COLUMN `cate1_id` INTEGER NOT NULL DEFAULT 0 COMMENT '一级分类 ID',
  MODIFY COLUMN `cate2_id` INTEGER NOT NULL DEFAULT 0 COMMENT '二级分类 ID',
  MODIFY COLUMN `cate3_id` INTEGER NOT NULL DEFAULT 0 COMMENT '三级分类 ID（二层级级时与叶子类目一致）',
  MODIFY COLUMN `category_path` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分类路径，逗号分隔 1,2,3',
  MODIFY COLUMN `main_image` VARCHAR(512) NOT NULL COMMENT '主图 URL',
  MODIFY COLUMN `images_json` JSON NOT NULL DEFAULT ('[]') COMMENT '轮播图 JSON 数组',
  MODIFY COLUMN `spec_type` INTEGER NOT NULL DEFAULT 0 COMMENT '规格类型 0单规格 1多规格',
  MODIFY COLUMN `attr_json` JSON NULL COMMENT '商品参数 JSON',
  MODIFY COLUMN `tag_list` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '标签，逗号分隔',
  MODIFY COLUMN `market_price` INTEGER NOT NULL DEFAULT 0 COMMENT '市场价/划线价，单位：分',
  MODIFY COLUMN `cost_price` INTEGER NOT NULL DEFAULT 0 COMMENT '成本价，单位：分',
  MODIFY COLUMN `vip_price` INTEGER NOT NULL DEFAULT 0 COMMENT '会员价，单位：分',
  MODIFY COLUMN `unit` VARCHAR(20) NOT NULL DEFAULT '件' COMMENT '计价单位',
  MODIFY COLUMN `weight` INTEGER NOT NULL DEFAULT 0 COMMENT '重量，克',
  MODIFY COLUMN `volume` INTEGER NOT NULL DEFAULT 0 COMMENT '体积，立方厘米',
  MODIFY COLUMN `total_stock` INTEGER NOT NULL DEFAULT 0 COMMENT '总库存（SKU 汇总）',
  MODIFY COLUMN `sale_num` INTEGER NOT NULL DEFAULT 0 COMMENT '累计销量',
  MODIFY COLUMN `warn_stock` INTEGER NOT NULL DEFAULT 10 COMMENT '库存预警值',
  MODIFY COLUMN `express_id` INTEGER NOT NULL DEFAULT 0 COMMENT '运费模板 ID',
  MODIFY COLUMN `freight_type` INTEGER NOT NULL DEFAULT 0 COMMENT '包邮 0否 1是',
  MODIFY COLUMN `limit_buy` INTEGER NOT NULL DEFAULT 0 COMMENT '限购数量 0不限',
  MODIFY COLUMN `is_new` BOOLEAN NOT NULL DEFAULT false COMMENT '是否新品',
  MODIFY COLUMN `is_hot` BOOLEAN NOT NULL DEFAULT false COMMENT '是否热销',
  MODIFY COLUMN `is_recommend` BOOLEAN NOT NULL DEFAULT false COMMENT '是否首页推荐',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'NOT_LISTED' COMMENT '商品状态 SpuStatus 枚举字符串',
  MODIFY COLUMN `sort` INTEGER NOT NULL DEFAULT 0 COMMENT '排序权重',
  MODIFY COLUMN `putaway_time` DATETIME(3) NULL COMMENT '上架时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间';

ALTER TABLE `skus` COMMENT = '商品 SKU（规格库存售价）';
ALTER TABLE `skus`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT 'SKU 主键 ID',
  MODIFY COLUMN `spu_id` INTEGER NOT NULL COMMENT '所属 SPU ID',
  MODIFY COLUMN `specs_json` JSON NOT NULL COMMENT '规格 JSON，如 {"颜色":"红","尺码":"L"}',
  MODIFY COLUMN `price` INTEGER NOT NULL COMMENT '售价，单位：分',
  MODIFY COLUMN `stock` INTEGER NOT NULL DEFAULT 0 COMMENT '可售库存',
  MODIFY COLUMN `reserved` INTEGER NOT NULL DEFAULT 0 COMMENT '预占库存（待支付订单）',
  MODIFY COLUMN `version` INTEGER NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  MODIFY COLUMN `barcode` VARCHAR(64) NULL COMMENT '条形码',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED / DISABLED';

ALTER TABLE `cart_items` COMMENT = '购物车行';
ALTER TABLE `cart_items`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '购物车行主键 ID',
  MODIFY COLUMN `user_id` INTEGER NOT NULL COMMENT '用户 ID',
  MODIFY COLUMN `sku_id` INTEGER NOT NULL COMMENT 'SKU ID',
  MODIFY COLUMN `quantity` INTEGER NOT NULL DEFAULT 1 COMMENT '数量',
  MODIFY COLUMN `selected` BOOLEAN NOT NULL DEFAULT true COMMENT '是否勾选结算';

ALTER TABLE `addresses` COMMENT = '用户收货地址';
ALTER TABLE `addresses`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '地址主键 ID',
  MODIFY COLUMN `user_id` INTEGER NOT NULL COMMENT '用户 ID',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '收货人姓名',
  MODIFY COLUMN `phone` VARCHAR(20) NOT NULL COMMENT '收货人手机',
  MODIFY COLUMN `province` VARCHAR(64) NOT NULL COMMENT '省',
  MODIFY COLUMN `city` VARCHAR(64) NOT NULL COMMENT '市',
  MODIFY COLUMN `district` VARCHAR(64) NOT NULL COMMENT '区/县',
  MODIFY COLUMN `detail` VARCHAR(255) NOT NULL COMMENT '详细地址',
  MODIFY COLUMN `is_default` BOOLEAN NOT NULL DEFAULT false COMMENT '是否默认地址';

ALTER TABLE `orders` COMMENT = '订单主表';
ALTER TABLE `orders`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '订单主键 ID',
  MODIFY COLUMN `order_no` VARCHAR(32) NOT NULL COMMENT '订单号',
  MODIFY COLUMN `user_id` INTEGER NOT NULL COMMENT '用户 ID',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '订单状态 OrderStatus',
  MODIFY COLUMN `total_amount` INTEGER NOT NULL COMMENT '商品总金额，分',
  MODIFY COLUMN `pay_amount` INTEGER NOT NULL COMMENT '实付金额，分',
  MODIFY COLUMN `remark` VARCHAR(255) NULL COMMENT '买家留言',
  MODIFY COLUMN `address_json` JSON NOT NULL COMMENT '收货地址快照 JSON',
  MODIFY COLUMN `logistics_json` JSON NULL COMMENT '物流信息 JSON',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间';

ALTER TABLE `order_items` COMMENT = '订单商品行';
ALTER TABLE `order_items`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '订单行主键 ID',
  MODIFY COLUMN `order_id` INTEGER NOT NULL COMMENT '订单 ID',
  MODIFY COLUMN `sku_id` INTEGER NOT NULL COMMENT 'SKU ID',
  MODIFY COLUMN `spu_title` VARCHAR(255) NOT NULL COMMENT '下单时 SPU 标题快照',
  MODIFY COLUMN `specs_json` JSON NOT NULL COMMENT '规格快照 JSON',
  MODIFY COLUMN `unit_price` INTEGER NOT NULL COMMENT '成交单价，分',
  MODIFY COLUMN `quantity` INTEGER NOT NULL COMMENT '购买数量';

ALTER TABLE `order_status_logs` COMMENT = '订单状态变更日志';
ALTER TABLE `order_status_logs`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '日志主键 ID',
  MODIFY COLUMN `order_id` INTEGER NOT NULL COMMENT '订单 ID',
  MODIFY COLUMN `from_status` VARCHAR(32) NULL COMMENT '原状态',
  MODIFY COLUMN `to_status` VARCHAR(32) NOT NULL COMMENT '新状态',
  MODIFY COLUMN `operator` VARCHAR(64) NULL COMMENT '操作人',
  MODIFY COLUMN `remark` VARCHAR(255) NULL COMMENT '备注',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE `inventory_reservations` COMMENT = '库存预占记录（待支付）';
ALTER TABLE `inventory_reservations`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '预占记录 ID',
  MODIFY COLUMN `order_id` INTEGER NOT NULL COMMENT '订单 ID',
  MODIFY COLUMN `sku_id` INTEGER NOT NULL COMMENT 'SKU ID',
  MODIFY COLUMN `quantity` INTEGER NOT NULL COMMENT '预占数量',
  MODIFY COLUMN `expire_at` DATETIME(3) NOT NULL COMMENT '过期时间';

ALTER TABLE `payments` COMMENT = '支付单';
ALTER TABLE `payments`
  MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT '支付单主键 ID',
  MODIFY COLUMN `payment_no` VARCHAR(32) NOT NULL COMMENT '支付流水号',
  MODIFY COLUMN `order_id` INTEGER NOT NULL COMMENT '订单 ID',
  MODIFY COLUMN `channel` VARCHAR(32) NOT NULL COMMENT '支付渠道 ALIPAY / WECHAT',
  MODIFY COLUMN `amount` INTEGER NOT NULL COMMENT '支付金额，分',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT '支付状态 INIT / SUCCESS / CLOSED',
  MODIFY COLUMN `notify_raw` JSON NULL COMMENT '第三方回调原始 JSON',
  MODIFY COLUMN `paid_at` DATETIME(3) NULL COMMENT '支付成功时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';
